### ISSUE TITLE
Does plu-ts transpile to Plutus as an intermediate representation?

### ISSUE THREAD

**Issue by xhliu** [HarmonicLabs/plu-ts#5]
Or it compiles to Untyped Plutus Core directly?

**Comment by michele-nuzzi** [comment]
No; it compiles to Untyped Plutus Core directly!

It defines it's own representation of the UPLC AST in the [`src/onchain/UPLC`](https://github.com/HarmonicLabs/plu-ts/tree/main/src/onchain/UPLC) folder;

the compilation happens calling the `toUPLC` method of the [`Term`](https://github.com/HarmonicLabs/plu-ts/blob/main/src/onchain/pluts/Term/index.ts) class;
